public let DEEWM_WINDOW_ID = "DEEWM_WINDOW_ID"
public let DEEWM_WORKSPACE = "DEEWM_WORKSPACE"
public let DEEWM_FOCUSED_WORKSPACE = "DEEWM_FOCUSED_WORKSPACE"
public let DEEWM_PREV_WORKSPACE = "DEEWM_PREV_WORKSPACE"
